- name: Building and uploading Docker images to Docker Hub
  hosts: localhost

  vars:
    docker_repository: "0xd00d2bad/toad_cicd"
    docker_date_tag: "{{ ansible_date_time.date }}"

  tasks:
    - name: Remove image with latest tag
      become: yes
      docker_image:
        state: absent
        name: "{{ docker_repository }}"
        tag: "latest"
    - name: Remove image with current date tag
      become: yes
      docker_image:
        state: absent
        name: "{{ docker_repository }}"
        tag: "{{ docker_date_tag }}"

    - name: Building an image with the latest tag and push
      become: yes
      docker_image:
        source: build
        build:
          path: ./
          dockerfile: Dockerfile
          nocache: yes
        name: "{{ docker_repository }}"
        force_tag: true
        push: yes
      register: image_build

    - name: Added tag with current date and push
      become: yes
      docker_image:
        name: "{{ docker_repository }}"
        repository: "{{ docker_repository }}"
        tag: "{{ docker_date_tag }}"
        force_tag: true
        state: present
        push: yes
      when: image_build.changed
