- name: Budowanie i przesyłanie obrazów Docker do Docker Hub
  hosts: localhost

  vars:
    docker_repository: "0xd00d2bad/toad_cicd"

  tasks:
    - name: Build image
      community.docker.docker_image:
        name: "{{ docker_repository }}"
        build:
          path: .
        source: build
    - name: Tag and push to docker hub
      community.docker.docker_image:
        name: "{{ docker_repository }}"
        repository: "{{ docker_repository }}:{{ ansible_date_time.date }}"
        push: true
        source: local
    - name: Add tag latest to image
      community.docker.docker_image:
        name: "{{ docker_repository }}:{{ ansible_date_time.date }}"
        repository: "{{docker_repository}}:latest"
        force_tag: true
        source: local
        push: true

